from pathlib import Path

import pandas as pd
import streamlit as st

from src.scoring import calculate_points, DEFAULT_SCORING

PROJECT_ROOT = Path(__file__).resolve().parent

PREDICTIONS_PATH = PROJECT_ROOT / "data" / "processed" / "latest_predictions.csv"

REQUIRED_PREDICTION_COLUMNS = [
    "game_date",
    "pitcher",
    "team",
    "opponent",
    "location",
    "strikeouts",
    "outs",
    "hits",
    "earned_runs",
    "walks",
    "hit_batters",
    "win_probability",
    "projected_points",
    "prediction_for",
]

st.set_page_config(page_title="Fantasy Pitcher Predictor", page_icon="⚾", layout="wide")

@st.cache_data(ttl=300)

def load_latest_predictions():
    """Load the daily prediction output."""

    if not PREDICTIONS_PATH.exists():
        return pd.DataFrame()

    predictions = pd.read_csv(PREDICTIONS_PATH)

    missing_columns = [column for column in REQUIRED_PREDICTION_COLUMNS if column not in predictions.columns]

    if missing_columns:
        raise ValueError(f"latest_predictions.csv is missing required columns: {missing_columns}")

    if predictions.empty:
        return predictions

    predictions["game_date"] = pd.to_datetime(predictions["game_date"], errors="coerce")

    numeric_columns = [
        "strikeouts",
        "outs",
        "hits",
        "earned_runs",
        "walks",
        "hit_batters",
        "win_probability",
        "projected_points",
    ]

    for column in numeric_columns:
        if column in predictions.columns:
            predictions[column] = pd.to_numeric(predictions[column], errors="coerce")

    return predictions

def format_probability(value):
    """Convert probability to a percentage string."""

    if pd.isna(value):
        return "N/A"

    return f"{value * 100:.1f}%"


def get_prediction_row(predictions, pitcher, game_date=None):
    """Return the prediction row for a pitcher."""

    result = predictions[predictions["pitcher"].astype(str) == str(pitcher)].copy()

    if game_date is not None:
        result = result[result["game_date"].dt.date == game_date]

    if result.empty:
        return None

    return result.iloc[0]


def calculate_custom_points(row, scoring):
    """Calculate fantasy points from a prediction row."""

    prediction_dict = {
        "strikeouts": row["strikeouts"],
        "outs": row["outs"],
        "hits": row["hits"],
        "earned_runs": row["earned_runs"],
        "walks": row["walks"],
        "hit_batters": row["hit_batters"],
    }

    return calculate_points(prediction_dict, scoring=scoring)

predictions = load_latest_predictions()

st.title("⚾ Fantasy Pitcher Predictor")

st.write("Predict starting-pitcher performance across the full MLB slate.")

st.caption("Predictions are generated by the automated daily pipeline and loaded from the shared prediction output.")

if predictions.empty:
    st.warning("No daily predictions are currently available.")
    st.stop()

matchup_tab, browser_tab = st.tabs(["🎯 Matchup Predictor", "📊 Stat Browser"])

with matchup_tab:
    st.header("Matchup Predictor")

    available_dates = sorted(predictions["game_date"].dropna().dt.date.unique())

    if not available_dates:
        st.error("No prediction dates are available.")
        st.stop()

    selected_date = st.selectbox("Game Date", available_dates, format_func=lambda d: d.strftime("%B %d, %Y"))

    date_predictions = predictions[predictions["game_date"].dt.date == selected_date].copy()

    if date_predictions.empty:
        st.info("No predictions are available for this date.")

    else:
        pitcher_options = sorted(date_predictions["pitcher"].dropna().unique())

        selected_pitcher = st.selectbox("Pitcher", pitcher_options)

        selected_row = get_prediction_row(predictions, selected_pitcher, selected_date)

        if selected_row is None:
            st.error("Could not find a prediction for this pitcher.")

        else:
            st.subheader("Matchup")

            col1, col2, col3, col4 = st.columns(4)

            with col1:
                st.metric("Pitcher", selected_row["pitcher"])
            with col2:
                st.metric("Team", selected_row["team"])
            with col3:
                st.metric("Opponent", selected_row["opponent"])
            with col4:
                st.metric("Location", selected_row["location"])

            st.divider()

            st.subheader("Pitching Projections")

            col1, col2, col3 = st.columns(3)

            with col1:
                st.metric("Strikeouts", f"{selected_row['strikeouts']:.2f}")
            with col2:
                st.metric("Outs", f"{selected_row['outs']:.2f}")
            with col3:
                st.metric("Hits", f"{selected_row['hits']:.2f}")

            col1, col2, col3 = st.columns(3)

            with col1:
                st.metric("Earned Runs", f"{selected_row['earned_runs']:.2f}")
            with col2:
                st.metric("Walks", f"{selected_row['walks']:.2f}")
            with col3:
                st.metric("Hit Batters", f"{selected_row['hit_batters']:.2f}")

            st.divider()

            st.subheader("Win Probability")

            win_probability = selected_row["win_probability"]

            if pd.isna(win_probability):
                st.info("Win probability is unavailable for this matchup.")
            else:
                st.metric("Team Win Probability", format_probability(win_probability))
                st.progress(float(min(max(win_probability, 0.0), 1.0)))

            st.divider()

            st.subheader("Fantasy Projection")

            default_points = selected_row.get("projected_points", None)

            if pd.notna(default_points):
                st.metric("Projected Fantasy Points", f"{default_points:.2f}")

            with st.expander("Customize scoring"):
                st.write("Enter your league's scoring values. Values are applied to the projected pitching components above.")

                col1, col2 = st.columns(2)

                with col1:
                    strikeouts_points = st.number_input("Strikeouts", value=float(DEFAULT_SCORING["strikeouts"]), step=0.5)
                    outs_points = st.number_input("Outs", value=float(DEFAULT_SCORING["outs"]), step=0.5)
                    hits_points = st.number_input("Hits", value=float(DEFAULT_SCORING["hits"]), step=0.5)
                with col2:
                    earned_runs_points = st.number_input("Earned Runs", value=float(DEFAULT_SCORING["earned_runs"]), step=0.5)
                    walks_points = st.number_input("Walks", value=float(DEFAULT_SCORING["walks"]), step=0.5)
                    hit_batters_points = st.number_input("Hit Batters", value=float(DEFAULT_SCORING["hit_batters"]), step=0.5)

                custom_scoring = {
                    "strikeouts": strikeouts_points,
                    "outs": outs_points,
                    "hits": hits_points,
                    "earned_runs": earned_runs_points,
                    "walks": walks_points,
                    "hit_batters": hit_batters_points,
                }

                custom_points = calculate_custom_points(selected_row, custom_scoring)

                st.metric("Custom Projected Points", f"{custom_points:.2f}")

with browser_tab:
    st.header("Stat Browser")
    st.write("Scan the full slate for projected pitching performance.")

    available_dates = sorted(predictions["game_date"].dropna().dt.date.unique())

    selected_date = st.selectbox("Date", available_dates, format_func=lambda d: d.strftime("%B %d, %Y"), key="browser_date")

    browser_data = predictions[predictions["game_date"].dt.date == selected_date].copy()

    if browser_data.empty:
        st.info("No predictions are available for this date.")

    else:
        st.subheader("Filters")

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            teams = sorted(browser_data["team"].dropna().unique())
            selected_team = st.selectbox("Team", ["All"] + teams, key="browser_team")
        with col2:
            opponents = sorted(browser_data["opponent"].dropna().unique())
            selected_opponent = st.selectbox("Opponent", ["All"] + opponents, key="browser_opponent")
        with col3:
            locations = sorted(browser_data["location"].dropna().unique())
            selected_location = st.selectbox("Location", ["All"] + locations, key="browser_location")
        with col4:
            minimum_points = st.number_input("Minimum projected points", min_value=0.0, value=0.0, step=1.0, key="browser_min_points")

        if selected_team != "All":
            browser_data = browser_data[browser_data["team"] == selected_team]
        if selected_opponent != "All":
            browser_data = browser_data[browser_data["opponent"] == selected_opponent]
        if selected_location != "All":
            browser_data = browser_data[browser_data["location"] == selected_location]

        browser_data = browser_data[browser_data["projected_points"] >= minimum_points]

        display_columns = [
            "pitcher",
            "team",
            "opponent",
            "location",
            "strikeouts",
            "outs",
            "hits",
            "earned_runs",
            "walks",
            "hit_batters",
            "win_probability",
            "projected_points",
        ]

        display_data = browser_data[display_columns].copy()

        display_data = display_data.rename(
            columns={
                "pitcher": "Pitcher",
                "team": "Team",
                "opponent": "Opponent",
                "location": "Location",
                "strikeouts": "K",
                "outs": "Outs",
                "hits": "Hits",
                "earned_runs": "ER",
                "walks": "BB",
                "hit_batters": "HBP",
                "win_probability": "Win %",
                "projected_points": "Points",
            }
        )

        display_data["K"] = display_data["K"].round(2)
        display_data["Outs"] = display_data["Outs"].round(2)
        display_data["Hits"] = display_data["Hits"].round(2)
        display_data["ER"] = display_data["ER"].round(2)
        display_data["BB"] = display_data["BB"].round(2)
        display_data["HBP"] = display_data["HBP"].round(2)
        display_data["Points"] = display_data["Points"].round(2)
        display_data["Win %"] = (display_data["Win %"] * 100).round(1)
        display_data = display_data.sort_values("Points", ascending=False)

        st.caption(f"{len(display_data)} pitchers")
        st.dataframe(display_data, use_container_width=True, hide_index=True)

with st.expander("About the model"):
    st.write("The model uses pitcher performance, recent form, opponent offense, rest, park factors, team run support, and bullpen quality.")
    st.write("The daily prediction pipeline generates projections for strikeouts, outs, hits, earned runs, walks, hit batters, and team win probability.")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Strikeout MAE", "0.96 Ks")
    with col2:
        st.metric("Strikeout RMSE", "1.34 Ks")
    with col3:
        st.metric("Strikeout R²", "0.62")

st.divider()

st.caption("Fantasy Pitcher Predictor • 2026 MLB Statcast-based model")